CREATE TABLE Ugyfel_Masked (
    ID INT IDENTITY PRIMARY KEY,
 	LOGIN NVARCHAR(255) MASKED WITH (FUNCTION = 'default()'), 
    EMAIL NVARCHAR(255) MASKED WITH (FUNCTION = 'email()'),
    NEV NVARCHAR(255) MASKED WITH (FUNCTION = 'partial(1,"XXXXXX",1)'),
    SZULEV INT MASKED WITH (FUNCTION = 'random(1, 4)')NULL,
    NEM NVARCHAR(1) MASKED WITH (FUNCTION = 'default()') NULL,
    CIM NVARCHAR(255) MASKED WITH (FUNCTION = 'default()') NULL
);

INSERT INTO Ugyfel_Masked (LOGIN, EMAIL, NEV, SZULEV, NEM, CIM)
SELECT LOGIN, EMAIL, NEV, SZULEV, NEM, CIM
FROM Ugyfel;

CREATE USER UgyfelMaskedUser WITHOUT Login;
GRANT SELECT ON Ugyfel_Masked TO UgyfelMaskedUser

EXECUTE AS USER='UgyfelMaskedUser';
SELECT * 
FROM Ugyfel_Masked